<?php
class Ascii {
    public static function arrowLeft() {
		return json_decode('"\u2190"');
	}

	public static function arrowRight() {
		return json_decode('"\u2192"');
	}

	public static function arrowUp() {
		return json_decode('"\u2191"');
	}

	public static function arrowDown() {
		return json_decode('"\u2193"');
	}

	public static function upperLeft() {
        return json_decode('"\u250C"');
    }

    public static function singleDoubleUpperLeft() {
        return json_decode('"\u2552"');
    }

    public static function doubleSingleUpperLeft() {
        return json_decode('"\u2553"');
    }

    public static function doubledoubleUpperLeft() {
        return json_decode('"\u2554"');
    }

    public static function lowerLeft() {
        return json_decode('"\u2514"');
    }

    public static function singleDoubleLowerLeft() {
        return json_decode('"\u2558"');
    }

    public static function doubleSingleLowerLeft() {
        return json_decode('"\u2559"');
    }

    public static function doubleDoubleLowerLeft() {
        return json_decode('"\u255A"');
    }

    public static function upperRight() {
        return json_decode('"\u2510"');
    }

    public static function singleDoubleUpperRight() {
        return json_decode('"\u2556"');
    }

    public static function doubleSingleUpperRight() {
        return json_decode('"\u2555"');
    }

    public static function doubleDoubleUpperRight() {
        return json_decode('"\u2557"');
    }

    public static function lowerRight() {
        return json_decode('"\u2518"');
    }

    public static function singleDoubleLowerRight() {
        return json_decode('"\u255C"');
    }

    public static function doubleSingleLowerRight() {
        return json_decode('"\u255B"');
    }

    public static function doubleDoubleLowerRight() {
        return json_decode('"\u255D"');
    }

    public static function horizontal() {
        return json_decode('"\u2500"');
    }

    public static function doubleHorizontal() {
        return json_decode('"\u2550"');
    }

    public static function horizontalLeft() {        
        return json_decode('"\u2524"');
    }

    public static function doubleHorizontalLeft() {
        return json_decode('"\u2561"');
    }

    public static function horizontalRight() {
        return json_decode('"\u251C"');
    }

    public static function doubleHorizontalRight() {
        return json_decode('"\u255E"');
    }

    public static function vertical() {
        return json_decode('"\u2502"');
    }

    public static function doubleVertical() {
        return json_decode('"\u2551"');
    }

    public static function verticalTop() {
        return json_decode('"\u2534"');
    }

    public static function doubleVerticalTop() {
        return json_decode('"\u2568"');
    }

    public static function verticalBottom() {
        return json_decode('"\u252C"');
    }

    public static function doubleVerticalBottom() {
        return json_decode('"\u2565"');
    }
}